name: Build Theme ZIP

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get version from tag
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Update style.css version
        run: |
          awk -v v="$VERSION" '/^Version:/ {$0="Version: "v}1' style.css > tmp && mv tmp style.css

      - name: Remove git files
        run: |
          rm -rf .git
          rm -rf .github

      - name: Create theme folder
        run: |
          mkdir a-salah.dev
          shopt -s extglob
          mv !(a-salah.dev) a-salah.dev/

      - name: Zip theme
        run: |
          zip -r a-salah.zip a-salah.dev

      - name: Upload ZIP
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: a-salah.dev.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
