name: Build Theme ZIP

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Remove Git files
        run: |
          rm -rf .git
          rm -rf .github

      - name: Create theme folder
        run: |
          mkdir a-salah.dev
          shopt -s extglob
          mv !(a-salah.dev) a-salah.dev/

      - name: Zip theme
        run: |
          zip -r a-salah.dev.zip a-salah.dev

      - name: Upload ZIP to release
        uses: softprops/action-gh-release@v1
        with:
          files: a-salah.dev.zip